package-lock.json, src/scripts/express.js
Hey :wave:!
By default, `expressjs` listens on `0.0.0.0`/`::` ([see `net.Server`'s `server.listen([port[, host[, backlog]]][, callback])` documentation](https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback)) and I don't feel really confident with exposing random ports allowing to control my music playback on the Internet, so I updated it to listen on `127.0.0.1` instead :wink:.
If some people depend on being to control `tidal-hifi` from their local network, maybe the address should be replaced with a `host` field in `settings.apiSettings`.
Cheers!
=> Updated the express api to only listen on localhost

package.json, src/main.js, src/preload.js, src/scripts/discord.js, src/scripts/mediaInfo.js
I have tried adding the "hh:mm:ss left" function to Discord RPC I came on the idea as applications like PreMiD use it for YouTube Music(https://premid.app/store/presences/YouTube%20Music)
Due to some small delays when skipping parts of the song I feel like it could be improved on but so far it works without issues after 3-4 hours of fixing and debugging it.
~~EDIT: I have also realized just now that when it switches songs after it ends it pops up with browsing tidal for a second while it does the checks which is one of the things that also should be improved on.~~
=> Add 2 new fields to MediaInfo and an addition to Discord RPC

README.md
URL between brackets was missing 'https://'
=> Fixed #47 External links working

src/preload.js
Workaround until we can get last.fm integration to work directly utilizing the [rescrobbled](https://github.com/InputUsername/rescrobbled) project, as stated on [#11](https://github.com/Mastermindzh/tidal-hifi/pull/11#issuecomment-956143965)
This fixes the `xesam:artist` metadata field, and also provides the track length metadata field. The `player.getPosition` function is overridden to get the current time of the track. Finally, a `convertDuration` function is provided which converts the time in the Tidal UI (in MM:SS) to just be in seconds as an int, which makes formatting and unit conversion easier.
=> Update MPRIS functionality to provide length, artist, and current position

src/preload.js
Set the 'app-name' variable used by notify-send under Linux.
Before
After
Closes #7
=> Show "Tidal Hifi" as application name for notify-send notifications

.github/workflows/build.yml, .github/workflows/release.yml, build/electron-builder.yml, src/preload.js
Previous builds failed due to missing `bsdtar` build dependencies when building the package using the Github workflow Linux environment.
Fully working workflow can be seen [here](https://github.com/kevihiiin/tidal-hifi/actions/runs/1555060342).
The generated `tida-hifi.pacman` file can be installed and used under Arch Linux/Manjaro.
=> Generate pacman builds using Github workflows

src/preload.js
This compliments #84 as the album/song image would turn out pixelated/blurry since the default res the player uses in the image source is 80x80 instead of one of the high quality images
=> use higher resolution image for song/album cover

src/preload.js, src/scripts/discord.js, src/scripts/mediaInfo.js
Tries to get the album name and display it on the player module and on Discord as "LargeImageText".
- KDE media player
- Discord
Edit: Guess it fixes [this](https://github.com/Mastermindzh/tidal-hifi/issues/80) issue
=> Get album name

README.md
As I have recently changed the way the package handles the installation I also had to change the package name/base to include the -bin suffix so as follows I have also updated the readme to reflect this change.
=> Change tidal-hifi to tidal-hifi-bin for AUR

src/scripts/menu.js
When the try icon is enabled, the quit button in the menu only closes the window. I've made it actually quit the app
=> make quit button actually quit app

src/main.js, src/preload.js
Automatic muting sometimes failed, as did unmuting.
This is a fix for both those issues
=> Fix inconsistent auto-muting

build/electron-builder.base.yml
Category change is based on the QA Notice from Gentoo package manager: 
```
* QA Notice: This package installs one or more .desktop files that do not
* pass validation.
* 
* 	/usr/share/applications/tidal-hifi.desktop: error: (will be fatal in the future): value item "Audio" in key "Categories" in group "Desktop Entry" requires another category to be present among the following categories: AudioVideo
* 
```
The desktop name change may be subjective, but application desktop names usually start with capitalized letters and divide words with spaces. Now it looks kind of weird between other applications. I thought either **TIDAL**, **TIDAL Hi-Fi**, **Tidal** or **Tidal Hi-Fi** could look nice.
=> Update configuration of the desktop file

.vscode/settings.json, src/constants/settings.ts, src/constants/statuses.ts, src/features/listenbrainz/listenbrainz.ts, src/features/listenbrainz/models/storeData.ts, src/features/logger.ts, src/main.ts, src/pages/settings/preload.ts, src/pages/settings/settings.html, src/preload.ts, src/scripts/express.ts, src/scripts/mediaInfo.ts, src/scripts/settings.ts
This should close #253 
I also noticed that the two lines
```js
skippedArtists.value = settingsStore.get<string, string[]>(settings.skippedArtists).join("\n");
customCSS.value = settingsStore.get<string, string[]>(settings.customCSS).join("\n");
```
in refreshSettings seem to break the settings window as it can't run the refresh function due to those two lines throwing a `.join() is not a function` error I didn't fix this error but I thought I would let you know as I was also confused as to why my normal install of tidal-hifi does not show my actual settings and defaults to everything being off and empty.
=> Add ListenBrainz implementation

src/pages/settings/settings.html
The settings page is incorrectly showing 5.7.0 on version 5.7.1:
```
$ ls -l $(which tidal-hifi)
lrwxrwxrwx 4 root root 75 Jan  1  1970 /run/current-system/sw/bin/tidal-hifi -> /nix/store/rlzjslwz11i5h7l4byfk4557p1ns4025-tidal-hifi-5.7.1/bin/tidal-hifi
```
=> Bump tidal version string in settings.html

CHANGELOG.md, package.json, src/constants/settings.ts, src/pages/settings/preload.ts, src/pages/settings/settings.html, src/preload.ts, src/scripts/discord.ts, src/scripts/settings.ts
This PR adds two features to enhance the user's control over the discord integration:
- The ability to hide the current song from the discord activity and display a custom text instead
- The ability to customize the text that is shown when no song is playing
To implement these features, this PR introduces three new settings in the `discord` section of the configuration:
- `showSong` (boolean): This setting determines whether the current song is shown in the discord activity or not. If set to `true`, the current song will be displayed as usual. If set to `false`, the custom text specified by the `listeningText` setting will be shown instead.
- `idleText` (string): This setting specifies the text that is shown in the discord activity when no song is playing. The default value is `Browsing …
=> More customizable Discord-Presence

src/preload.ts
This change closes the previous notification if a new one comes up.
Before my notifications would get spammed full when the title changes. :)
=> feature: Track current notification to replace it on track change

src/models/mediaInfo.ts, src/models/mediaPlayerInfo.ts, src/models/repeatState.ts, src/preload.ts, src/scripts/mediaInfo.ts
This PR adds the shuffle and repeat state to the API for external applications to know what the current state is for display purposes. Ie. #393
=> Api Feature: Add shuffle and repeat state to API

src/scripts/discord.ts
**`/src/scripts/discord.ts:62`**
```ts
if (mediaInfo.album) {
if (mediaInfo.album.length < 2) {  // Fix for DiscordRPC 2 character minimum
presence.largeImageText = mediaInfo.album + " ";
}
else {
presence.largeImageText = mediaInfo.album;
}
}
```
Discord API doesn't like largeImageTexts with less than 2 characters, so to fix this issue I've added an extra space to the album name, which Discord automatically trims as trailing white-space anyway.
=> Fix issue #449 Discord RPC stuck on "Browsing Tidal"

src/constants/settings.ts, src/pages/settings/preload.ts, src/pages/settings/settings.html, src/scripts/discord.ts, src/scripts/settings.ts
Added an option to disable the discord idle status
=> Add option to disable the discord rpc idle text

src/scripts/discord.ts
The problem exists in the timing between the mediaInfo updates and the Date.now(), they had a 500 ms difference.
This offsets the Date.now by that difference and gets rid of the jitter while the song is playing.
The jitter still exists when jumping around the song or when a song starts but it stabilizes quickly.
=> Fix Discord RPC Timestamp jitter
